name: CI Verify

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          # Cambia la versión 10 a 9.15.9 para que coincida con tu package.json raíz
          # O podrías eliminar esta línea 'version' si siempre quieres que tome la de package.json
          version: 9.15.9 

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install deps (workspace)
        run: pnpm install --frozen-lockfile

      - name: Typecheck (tsc sin emitir)
        run: |
          pnpm -r exec tsc -p tsconfig.json --noEmit

      - name: Lint
        run: pnpm lint

      - name: Build app (dry)
        run: pnpm --filter app build
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: dummy
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: dummy
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: dummy
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: dummy
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: dummy
          NEXT_PUBLIC_FIREBASE_APP_ID: dummy
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: dummy
