name: Deploy Firebase Functions

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'packages/functions/**'
      - 'firebase.json'
      - '.github/workflows/firebase-functions-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Prepare credentials
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > $RUNNER_TEMP/gcp-key.json

      - name: Build Functions
        run: pnpm --filter functions build

      - name: Deploy Functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcp-key.json
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          firebase deploy --only functions --project "$FIREBASE_PROJECT_ID"
